spring.datasource.url=jdbc:postgresql://localhost:5432/db_cashmanagement_dev
spring.datasource.username=devuser
spring.datasource.password=devpassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true